apiVersion: v1
kind: Namespace
metadata:
  name: shipzen-build
  labels:
    shipzen.jeneeldumasia.codes/system: "true"
    # Build pods require elevated permissions:
    # - buildkit rootless needs seccompProfile=Unconfined + apparmor unconfined
    # - BuildpackBuilder pack/dind needs privileged=true
    # "privileged" PSS level allows all of the above.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
