apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: shipzen-build-exception
  namespace: shipzen-build
spec:
  exceptions:
    - policyName: "*"
      ruleNames:
        - "privileged"
        - "autogen-privileged"
        - "host-namespaces"
        - "autogen-host-namespaces"
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Job
          namespaces:
            - shipzen-build
