apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shipzen-github
  namespace: shipzen-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: shipzen-github
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: shipzen/github
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: shipzen/github
        property: client_secret
    - secretKey: app_webhook_secret
      remoteRef:
        key: shipzen/github
        property: app_webhook_secret
