apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shipzen-auth-secret
  namespace: shipzen-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: shipzen-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: auth_secret
      remoteRef:
        key: shipzen/auth-secret
        property: value
