apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipzen-worker-sa
  namespace: shipzen-system
  annotations:
    iam.gke.io/gcp-service-account: "shipzen-builder-sa@YOUR_GCP_PROJECT_ID.iam.gserviceaccount.com"
automountServiceAccountToken: true # Worker now orchestrates Builder jobs in K8s
