apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Top-level kustomization for ArgoCD.
# ArgoCD syncs path: infra which resolves to this file.
# Every sub-directory that has a kustomization.yaml is listed here.
resources:
  - system/
  - controller/
  - worker/
  - api/
  - scale/
  - ui/
images:
  - name: shipzen-api
    newTag: sha-00f16a7

  - name: shipzen-controller
    newTag: sha-00f16a7

  - name: shipzen-worker
    newTag: sha-00f16a7

  - name: shipzen-builder
    newTag: latest

  - name: shipzen-ui
    newTag: sha-00f16a7

