apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shipzen-controller-pdb
  namespace: shipzen-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: shipzen-controller
