apiVersion: v1
kind: Service
metadata:
  name: shipzen-api
  namespace: shipzen-system
  labels:
    app: shipzen-api
spec:
  type: ClusterIP
  selector:
    app: shipzen-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
